# Generated by Django 3.2.9 on 2022-01-31 10:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('separator', models.CharField(max_length=1)),
                ('stringCharacter', models.CharField(max_length=1)),
                ('columns', models.JSONField()),
                ('modified', models.DateTimeField(default=datetime.datetime(2022, 1, 31, 10, 23, 0, 352180))),
                ('author_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(blank=True, null=True)),
                ('path_to_file', models.URLField(blank=True, null=True)),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schemas.schema')),
            ],
        ),
    ]
