# Generated by Django 3.2.9 on 2022-01-31 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 16, 9, 47, 739978)),
        ),
    ]
