# Generated by Django 3.2.9 on 2022-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='author',
            new_name='author_id',
        ),
    ]
