# Generated by Django 3.2.9 on 2022-01-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_rename_author_schema_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 13, 15, 18, 198510)),
        ),
    ]
