# Generated by Django 3.2.9 on 2022-03-30 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_schema_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 15, 37, 51, 574956)),
        ),
    ]
